### ISSUE TITLE
Cannot import default style sheet in Vue

### ISSUE THREAD

**Issue by crystalfp** [kouts/vue-search-input#1]
I'm trying your promising component, but a `import "vue-search-input/dist/styles.css";` inside the `<script>` section of a SFC file or `@use "node_modules/vue-search-input/dist/styles.css";` in the `<style>` section gives the following error: `Error: Missing "./dist/styles.css" export in "vue-search-input" package` even crashing the vite dev server.
Any idea on what I'm doing wrong? I'm trying the example on your GitHub page.
Thanks!
mario

**Comment by kouts** [comment]
Hello @crystalfp, you can import the styles either from inside `script` or `style` tags in your Vue app.
```
<script>
import 'vue-search-input/dist/styles.css';
</script>
```
or
```
<style>
@import 'vue-search-input/dist/styles.css';
</style>
```
Checkout the Stackblitz example [here](https://stackblitz.com/edit/vue3-app-vxksg3?file=src/App.vue)

**Comment by crystalfp** [comment]
Thanks @kouts ! This is exactly what I'm doing. Anyway, seems the problem arises from `vite` that sometimes goes crazy.

**Comment by willtemperley** [comment]
I had the same issue. Adding an export to the package.json fixes this

https://github.com/kouts/vue-search-input/pull/3
