### ISSUE TITLE
type password has no asterisks to hide the password

### ISSUE THREAD

**Issue by coudys** [kouts/vue-search-input#17]
Hi, thanks a lot for the type password added to your vue-search-input. I am probably not seeing it, but how do I hide the input data behind asterisks. I couldn't figure it. Can you point me in the right direction? Same kind of a prop I am not aware of?

**Comment by kouts** [comment]
Hey @coudys thanks for reporting this issue, it's now fixed with a5d52569dc9d7e5d91464feb7d0d12984979a965
